#!/bin/bash
if [[ !$(/usr/bin/id -u) -ne 0 ]]; then
    echo "Do Not Run This As Root"
    exit
fi

set -e # halt on error
set -x # echo cmds before executing
set -u # fail on undefined variable
set -o pipefail # force pipelines to fail on fail

# npm run lint:fix
# npm run test

PROJECT=watcher-192720
IMAGE_NAME=feathers-rest-pipe
DEPLOY_NAME=feathers-rest-pipe
gcloud builds submit --tag gcr.io/$PROJECT/$IMAGE_NAME
gcloud run deploy $DEPLOY_NAME --image gcr.io/$PROJECT/$IMAGE_NAME --platform managed

# gcloud builds list
